Fix https://github.com/barryvdh/laravel-ide-helper/issues/627
barryvdh/laravel-ide-helper pull request #1005
Opened 2020-08-05 14:00 UTC by SavKS

2020-08-05 14:36 UTC, mfn commented
For the lazy: https://github.com/barryvdh/laravel-ide-helper/issues/627

Would be great to receive some tests for this!

2020-09-06 21:13 UTC, mfn requested changes
@SavKS there's a lot of ground to cover the feature sounds super-interesting!

We haven't heard back, are you still interested in finish the PR?

I think due to the complexity, some tests are definitely on order here, what do you think?

2020-09-07 07:15 UTC, SavKS commented
@mfn 

I'm sorry, but I can't write tests. If anyone in the community has the opportunity to do so, I would be grateful for that.

2020-09-07 07:45 UTC, mfn commented
Thanks for the update!

This changes are quite involved I'm leaning towards having tests is a must.

I don't intend to do this myself, so let's keep the PR open if someone volunteers to step up!

2020-09-25 21:23 UTC, SeinopSys commented
I spend a good two hours trying to write tests for this but it seems like the `GeneratorCommand` class uses some special magic to detect facades which I was not able to replicate. Below is my unsuccessful attempt in case someone is able to build on it in any capacity.

```diff
Index: src/Method.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Method.php	(revision 39e2e8e2bcade1c9fbd2f5a3da7ea7f105c20206)
+++ src/Method.php	(date 1601068825567)
@@ -46,7 +46,7 @@
      * @param \ReflectionClass $class
      * @param string|null $methodName
      * @param array $interfaces
-     * @param NamespaceUses $namespaceUses
+     * @param NamespaceUses|null $namespaceUses
      */
     public function __construct(
         $method,
Index: src/Console/GeneratorCommand.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Console/GeneratorCommand.php	(revision 39e2e8e2bcade1c9fbd2f5a3da7ea7f105c20206)
+++ src/Console/GeneratorCommand.php	(date 1601060442663)
@@ -58,11 +58,9 @@
      * @param \Illuminate\View\Factory $view
      */
     public function __construct(
-        /*ConfigRepository */
-        $config,
+        \Illuminate\Config\Repository $config,
         Filesystem $files,
-        /* Illuminate\View\Factory */
-        $view
+        \Illuminate\View\Factory $view
     ) {
         $this->config = $config;
         $this->files = $files;
Index: tests/TestCase.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/TestCase.php	(revision 39e2e8e2bcade1c9fbd2f5a3da7ea7f105c20206)
+++ tests/TestCase.php	(date 1601064080820)
@@ -65,6 +65,15 @@
                 return file_get_contents($file);
             });
 
+        $mockFilesystem
+            ->shouldReceive('exists')
+            ->andReturnUsing(function ($file) {
+                return file_exists($file);
+            });
+
+        $mockFilesystem
+            ->shouldReceive('getRequire');
+
         $mockFilesystem
             ->shouldReceive('put')
             ->with(
Index: tests/Console/GeneratorCommand/RelativeClassNames/Test.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/Console/GeneratorCommand/RelativeClassNames/Test.php	(date 1601068862904)
+++ tests/Console/GeneratorCommand/RelativeClassNames/Test.php	(date 1601068862904)
@@ -0,0 +1,64 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Barryvdh\LaravelIdeHelper\Tests\Console\GeneratorCommand\RelativeClassNames;
+
+use Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider;
+use Barryvdh\LaravelIdeHelper\Tests\Console\GeneratorCommand\RelativeClassNames\ExternalDependency\ExternalServiceProvider;
+use Barryvdh\LaravelIdeHelper\Tests\SnapshotPhpDriver;
+use Barryvdh\LaravelIdeHelper\Tests\TestCase;
+use Illuminate\Support\Facades\View;
+use Illuminate\View\FileViewFinder;
+
+class Test extends TestCase {
+    /** @var string */
+    private $cwd;
+
+    /** @var FileViewFinder */
+    private $viewFinder;
+
+    protected function setUp():void {
+        parent::setUp();
+
+        new ExternalServiceProvider($this->app);
+
+        $this->cwd = getcwd();
+
+        $this->viewFinder = View::getFinder();
+
+        $this->mockFilesystem();
+
+        View::setFinder(new FileViewFinder(app()->get('files'), [
+            realpath(__DIR__).'/../../../../resources/views',
+        ]));
+    }
+
+    protected function tearDown():void {
+        chdir($this->cwd);
+
+        View::setFinder($this->viewFinder);
+
+        parent::tearDown();
+    }
+
+    public function testCommand():void {
+        chdir(__DIR__);
+
+        $result = $this->artisan('ide-helper:generate');
+
+        $result->assertExitCode(0);
+        $this->assertMatchesSnapshot($this->mockFilesystemOutput, new SnapshotPhpDriver());
+    }
+
+    /**
+     * Get package providers.
+     *
+     * @param \Illuminate\Foundation\Application $app
+     *
+     * @return array
+     */
+    protected function getPackageProviders($app) {
+        return [IdeHelperServiceProvider::class];
+    }
+}
Index: src/NamespaceUses.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/NamespaceUses.php	(revision 39e2e8e2bcade1c9fbd2f5a3da7ea7f105c20206)
+++ src/NamespaceUses.php	(date 1601068825567)
@@ -30,7 +30,7 @@
     /**
      * @var array
      */
-    public $classAliases;
+    public $classAliases = [];
 
     /**
      * NamespaceUses constructor.
@@ -60,11 +60,17 @@
     {
         $parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
 
+        $fileName = (new \ReflectionClass($this->classFQN))->getFileName();
+
+        if (!file_exists($fileName)) {
+            return;
+        }
+
         /** @var Namespace_ $namespaceData */
         $namespaceData = Arr::first(
             $parser->parse(
                 file_get_contents(
-                    (new \ReflectionClass($this->classFQN))->getFileName()
+                    $fileName
                 )
             ),
             function ($node) {
```

2020-09-28 03:52 UTC, mfn commented
:-(

I made a note to take a look sometime later, thanks!

2020-12-02 21:32 UTC, mfn commented
> I made a note to take a look sometime later, thanks!

I did make a note but coming back to this, I don't feel like having the energy going through this without any test coverage.

I'm happy to assist anyone else taking a stab a this tough, just create a new PR with this commit and hack away and ping me. It's easier to talk about this in PRs with actual code then with sharing ZIPs.

2020-12-05 21:01 UTC, mfn commented
It looks like with the recent update to this PR something went wrong with a merge? I should not see so many unrelated changes here.

Please fix this and update with master and resolve the merge conflicts, thank you

2020-12-21 08:42 UTC, barryvdh submitted a review, later dismissed

2020-12-21 09:10 UTC, mfn reviewed
Personally I still don't feel confident merging this with 0 tests

2021-02-17 19:37 UTC, SavKS commented
Tests were added with the help of @Tarik02.

2021-03-12 13:58 UTC, mfn requested changes
Approach LGTM and tested it also on a real life project 🎉 

Some technical nitpicks, please see feedback inline

2021-03-12 13:58 UTC, mfn commented on src/UsesResolver.php
> +            $alias = class_basename($classFQN);
Unfortunately can't use global functions from Support/helpers.php in a library.

ide-helper, whilst Laravel specific, may be used just with its individual illuminate/* packages and must not depend on such functions.

Fix in this case: sorry, just copypaste the code over 😬

2021-03-12 13:58 UTC, mfn commented on src/UsesResolver.php
> +    protected $classAliases = [];
From a design perspective of this class, I suggest to make it stateless as there's no benefit to it.

Suggest approach:
- get rid of this property
- just return the data array from `loadFromCode`
- get rid of `addClassAlias
- change all the `load*` methods to just return the data you return from `loadFromCode`
- which means the call in `\Barryvdh\LaravelIdeHelper\Alias::__construct` is just `(new UsesResolver())->loadFromClass($this->root);`
- adapt test

Most classes in this library have their fair share of states, which is nightmare to trace properly.

2021-03-14 19:10 UTC, mfn approved these changes
LGTM!

If you could add a README entry, I think we've good to go!

2021-03-15 06:45 UTC, merged

2021-03-15 07:42 UTC, mfn commented
> If you could add a README entry, I think we've good to go!

PS: I meant changelog of course -> already made a PR https://github.com/barryvdh/laravel-ide-helper/pull/1176