Allow casts with a return type of static or this to reference themselves
barryvdh/laravel-ide-helper pull request #1103
Opened 2020-12-02 02:05 UTC by hailwood

Right now a cast cannot specify that it returns static or this.
Allowing so would mean a new cast can extend the old one without having to redefine the get method (e.g. an Enum)
Presently if you specify static/this in the return type then those values are literally used which makes a property look like it returns an instance of the model itself.

2020-12-02 07:08 UTC, mfn commented
Can you please add a test showing the behavour change? Thank you!

2020-12-02 08:32 UTC, hailwood commented
Thanks for suggesting the tests @mfn, it made me realise a bug in my code :)

I've added hopefully thorough tests for all the different cases.
I also fixed an unrelated issue in another test due to a deprecated phpunit method being used.

2020-12-02 22:25 UTC, mfn requested changes
PR LGTM!

However, can you please undo the unrelated phpunit changes as outlined?

Thank you!

2020-12-02 22:25 UTC, mfn commented on tests/Console/EloquentCommandTest.php
> +        }
Please revert these changes; assertRegExp works fine; the warning may be annoying but IMHO no need for duping the code here.

2020-12-03 07:06 UTC, hailwood commented
@mfn All done :)

2020-12-03 08:45 UTC, mfn commented
@hailwood great!

sorry forgot, please add a changelog (also next time: please don't delete the PR template, it's there for a reason to be reminded of such things, thank you!)

2020-12-03 08:45 UTC, mfn approved these changes
Thank you 🤗 

@barryvdh LGTM for merge!

2020-12-03 09:14 UTC, hailwood commented
Thanks @mfn 
I normally keep the PR template, I think grammarly wiped it out sorry!

What would you put in the Changelog?
Thinking under Fixed 

- Casts with a return type of `static` or `$this` correctly resolve to an instance of the cast [\#1103 / riesjart](https://github.com/barryvdh/laravel-ide-helper/pull/1103)

2020-12-03 09:43 UTC, mfn commented
@hailwood yeah, sounds good to me!

2020-12-04 06:33 UTC, merged