add comments like table columns.
barryvdh/laravel-ide-helper pull request #1168
Opened 2021-03-05 08:16 UTC by biiiiiigmonster

## Summary

In order to better support ide, relations and getters/setters can also add comments like table columns. Only based on DocBlock, use `@comment`.
### Support list

- getter
- setter
- scope
- relations

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist
- [ ] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [x] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

2021-03-05 13:24 UTC, mfn requested changes
Despite you ticking off the checkbox, I don't see any tests:
![image](https://user-images.githubusercontent.com/87493/110121159-55b33c00-7dbe-11eb-9683-4f55e7fe09f5.png)

Can you please add one before someone reviews the code?
Thank you!

2021-03-07 12:43 UTC, biiiiiigmonster commented
I'm sorry that just did a local test, I'll make unit-test it up later.

2021-03-08 06:38 UTC, biiiiiigmonster commented
@mfn I have committed the unit test code, please see if it meets the requirements.

2021-03-12 13:28 UTC, mfn reviewed
What happens if both a getter and a setter has a `@comment`?

2021-03-13 07:08 UTC, biiiiiigmonster commented
I'm not quite sure that you mean, i guess you mean when getter and setter have the same name?

If so, i just tested it, this property will not become two(`@property-read`&`@property-write`), but one(`@property`), and the 
comment for this property will be anchoring the getter. If the getter doesn't have `@comment`, then this property don't either.

The simple code case
```php
class User
{
    /**
     * @comment I'm a setter.
     */
    public function setFullNameAttribute(): void
    {}

    /**
     * @comment I'm a getter.(If I don't exist, so will the property)
     */
    public function getFullNameAttribute(): string
    {}
}

// =>

/**
 * @property string $full_name I'm a getter.(If I don't exist, so will the property)
 * …
 */
```

2021-03-13 19:40 UTC, mfn approved these changes
LGTM!

- I added a suggestion to improve the README
- change you please add a changelog entry?

2021-03-13 19:40 UTC, mfn commented on README.md
> +In order to better support ide, relations and getters/setters can also add comments like table columns. Only based on DocBlock, use `@comment`. example:
```suggestion
In order to better support IDEs, relations and getters/setters can also add a comment to a property like table columns. Therefore a custom docblock `@comment` is used:
```

2021-03-14 13:18 UTC, biiiiiigmonster commented
OK, i got it :)

2021-03-15 06:52 UTC, merged