Support Laravel 8.77 Attributes
barryvdh/laravel-ide-helper pull request #1289
Opened 2021-12-30 07:58 UTC by SimonJnsson

## Summary
This PR adds support for the new Attribute syntax added in Laravel 8.77, added by https://github.com/laravel/framework/pull/40022.

Using Reflection on the get/set method provided to the Attribute, we can determine the return type of the getter and setter.

Below is an example usage (also found in added test).

```php
use Illuminate\Database\Eloquent\Casts\Attribute;

class Users extends Model
{
    public function name(): Attribute
    {
        return new Attribute(
            get: function (?string $name): ?string {
                return $name;
            },
            set: function (?string $name): ?string {
                return $name === null ? null : ucfirst($name);
            }
        );
    }
}

// => after generate models

/**
 * App\Models\Users
 * 
 * @property string|null $name
 * …
 */
```

## Type of change

This PR should be non breaking, but will however require laravel/framework >= 8.77 to work.

- [x] New feature (non-breaking change which adds functionality)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [] Add a CHANGELOG.md entry
- [x] Code style has been fixed via `composer fix-style`

2021-12-30 14:31 UTC, mfn requested changes
Approach overall LGTM thus I enabled running the tests, but they are failing for some of the PHP versions we need to support.

Can you please check this?

2021-12-30 14:34 UTC, SimonJnsson commented
> Approach overall LGTM thus I enabled running the tests, but they are failing for some of the PHP versions we need to support.
> 
> Can you please check this?

Thanks for taking the time to look at it! I'll get to work on the changes as soon as I get the time 👍

2021-12-30 22:25 UTC, barryvdh commented
Looks good. I would just skip the tests when the attribute doesn't exist :)

2022-01-03 07:43 UTC, SimonJnsson commented
@mfn i've updated the code to not use code that's incompatible with php 7.3. This should fix the failing unit test.

In regards to the failing integration tests, i'm a bit unsure why these are failing as it seems to somehow be happening when installing dependencies. Any pointers would be greatly appreciated.

2022-01-03 07:45 UTC, SimonJnsson commented
@barryvdh sounds good, i've added a check for existance of the Attribute class in the test :+1:

2022-01-03 08:18 UTC, mfn approved these changes
Tests green, change LGTM!

> In regards to the failing integration tests

See no failing tests? 🤔

2022-01-03 08:26 UTC, SimonJnsson commented
> 

I was referring to this https://github.com/barryvdh/laravel-ide-helper/runs/4667417056?check_suite_focus=true

But it might've been a random one-off as it sees to be gone now :+1:

2022-01-03 09:02 UTC, merged