Add support for composite keys
barryvdh/laravel-ide-helper pull request #1479
Opened 2023-11-06 19:58 UTC by CalebDW

Fixes #1474, https://github.com/topclaudy/compoships/issues/77

## Summary

Hello!

This PR adds support for relationships with composite keys. There have been a couple of issues over the years about this but this still has not been resolved (I don't want to have to extend the Artisan command in my app):

- https://github.com/barryvdh/laravel-ide-helper/issues/838
- https://github.com/barryvdh/laravel-ide-helper/issues/706

There's even an open issue on the Compoship side of things (https://github.com/topclaudy/compoships/issues/77) but as the maintainer stated, there really nothing to do on that end.

I understand Laravel does not support composite keys, however, people do use them and this package already provides the ability to define non-Laravel relations so it would be much easier to support this rather than to expect everyone who uses composite keys to have to extend the Artisan command with the same custom logic.

Thanks!

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

2024-01-01 22:22 UTC, calebdw commented
@mfn, would it be possible to review this PR please?

Thanks!

2024-02-07 20:18 UTC, barryvdh commented
Can we have a test for this?

2024-02-07 20:18 UTC, barryvdh requested changes
Can you add some tests?

2024-02-08 05:55 UTC, barryvdh commented
Do we need that package to test it? Or can we replicate a simple case here?

2024-02-08 05:57 UTC, calebdw commented
I'm working on a test at the moment, I don't think we need the package

2024-02-08 06:20 UTC, calebdw commented
Test has been added

2024-02-08 06:42 UTC, merged

2024-02-08 06:42 UTC, barryvdh commented
Thanks!

2024-02-08 06:43 UTC, calebdw commented
Thank you!!